springfox configuration and api documentation
Fleskimiso/invoicing-system-dawid-pawlowicz pull request #12
Opened 2023-07-14 13:43 UTC by Fleskimiso

2023-07-15 10:00 UTC, kamilDzietczyk approved these changes

2023-07-20 13:05 UTC, BartoszKamyszek requested changes

2023-07-20 13:05 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/controller/InvoiceControllerInterface.java
> +public interface InvoiceControllerInterface {
Trochę słaba nazwa, Staramy się raczej nadawać bardziej znaczące nazwy niż dopisywać na końcu słowo interface, nie mówi ono nic o tym co się tutaj znajduje. Przy wydzielaniu interfejsu też nie chcemy bezpośrednio wskazywać, że ten interfejs ma służyć tylko kontrolerom.

2023-07-20 13:05 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/model/Company.java
> +  @ApiModelProperty(value = "Company address", required = true, example = "ul.***, 00-000 *****")
możesz podać jakiś konkretny adres, ma on jednak służyć do zakładania invoice przez swaggera

2023-07-20 13:05 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/model/Company.java
> +  @ApiModelProperty(value = "Tax id number", required = true, example = "000-000-00-00")
uspójnij proszę ten taxId z tym co znajduje się w testHelpers, pewnie masz tutaj rozjazd jak ma być podawany ten numer, myślniki mają później znaczenie przy porównywaniu danych

2023-07-20 17:31 UTC, BartoszKamyszek approved these changes

2023-07-20 17:32 UTC, merged