Task 9/tax calculator
Fleskimiso/invoicing-system-dawid-pawlowicz pull request #16
Opened 2023-07-25 17:39 UTC by Fleskimiso

2023-07-25 17:43 UTC, kamilDzietczyk approved these changes

2023-07-26 16:41 UTC, BartoszKamyszek requested changes

2023-07-26 16:41 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/controller/tax/TaxCalculator.java
> +package pl.futurecollars.invoicing.controller.tax;
Jeśli dodajesz nowy pakiet na tax, to invoice też pprzenieś do odpowiedniego pakietu

2023-07-26 16:41 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/model/TaxCalculatorResult.java
> +package pl.futurecollars.invoicing.model;
ta klasa jest raczej modelem na poziomie wymiany danych, a nie modelem bazodanowym, więc oddzielmy go od tych z pakietu model. Po ang taka klasa to DTO, data transfer object i może być w pakiecie controllera, albo service

2023-07-26 16:41 UTC, BartoszKamyszek commented on app/src/test/groovy/pl/futurecollars/invoicing/controller/TaxCalculatorControllerIntegrationTest.groovy
> +        jsonService.toObject(taxAsString, TaxCalculatorResult) }
jeśli stworzyłeś klase, w której trzymasz metody pomocnicze do testów controllera, to taka metoda również powinna tam się znaleźć

2023-07-26 16:41 UTC, BartoszKamyszek commented on app/src/test/groovy/pl/futurecollars/invoicing/controller/HelperController.groovy
> +class HelperController extends Specification{
formatowanie

2023-07-26 16:41 UTC, BartoszKamyszek commented on app/src/test/groovy/pl/futurecollars/invoicing/controller/InvoiceControllerIntegrationTest.groovy
>      private MockMvc mockMvc
dodałeś w tej klasie dziedziczenie po klasie pomocniczej, ale nie wykorzystujesz jej w pełni, np masz teraz w 2 miejscach zmienną ENDPOINT, jeśli jest ona w klasie nadrzędnej to możesz z niej skorzystać w klasie dziedziczącej. Przejrzyj proszę te testy i powyciągaj części wspólne, jeśli już podjąłeś decyzje o klasie pomocniczej

2023-07-26 16:41 UTC, BartoszKamyszek commented on app/src/test/groovy/pl/futurecollars/invoicing/controller/HelperController.groovy
> +class HelperController extends Specification{
nazwa HelperController sugeruje, że ta klasa jest controllerem, a nie jest. Sugeruję bardziej posującą nazwę do jej działania, czyli np ControllerTestHelper

2023-07-27 13:07 UTC, kamilDzietczyk approved these changes

2023-08-01 19:30 UTC, BartoszKamyszek approved these changes

2023-08-02 12:35 UTC, merged